version: "3.4"

x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-size: "5m"
      max-file: "10"
x-restart: &restart
  restart: always

services:
  main:
    image: denisgolius/net2ftp:latest
    # volumes:
    #   - /var/backup:/var/www/html/
    ports:
      - "80:8080"
    <<: *logging
    <<: *restart